### ISSUE TITLE
Auto Insetter unexpected behavior on nested child view controllers

### ISSUE THREAD

**Issue by divyeshmakwana96** [uias/AutoInsetter#11]
**What**
I have a nested hierarchy of View Controllers. The child view controller has a second level child controller which contains a scroll view. The view has a custom position and is aligned at the bottom. The auto insetter is setting inset and offset value of the scroll view.

**Why**
Since I am leveraging `automaticallyAdjustsChildInsets` property on the parent, I only want to disable this behavior on the 2nd level child only. Since the child is part of the view hierarchy the auto insetter engine is updating scroll view insets as well.

**Potential Solution**
If a subview has a first responder of a type UIViewController than we skip all it's subviews? An improvement would be to have a UIViewController property which can enable/disable this behavior.

**Comment by msaps** [comment]
@divyeshmakwana96 should be resolved in [AutoInsetter 1.6](https://github.com/uias/AutoInsetter/releases/tag/1.6.0) - and Tabman 2.2.1 (https://github.com/uias/Tabman/releases/tag/2.2.1) 🎉

**Comment by divyeshmakwana96** [comment]
@msaps Thank you!!!
